services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["sh", "-c", "sleep 30 && npm start"]
  
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
  
volumes:
  db_data: